---

- name: install packages
  become: true
  pacman:
    update_cache: yes
    name:
    - plasma-meta
    - kde-applications-meta

- name: enable display manager
  systemd:
    enabled: yes
    name: sddm
