---

- name: install packages
  become: true
  pacman:
    update_cache: yes
    name:
    - ttf-dejavu
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - ttf-liberation
    - tmux
    - vim
    - autojump

- name: configure fonts
  become: true
  file:
    src: /etc/fonts/conf.avail/{{ item }}
    dest: /etc/fonts/conf.d/{{ item }}
    state: link
  with_items:
  - 10-sub-pixel-rgb.conf
  - 11-lcdfilter-default.conf
